# Generated by Django 4.1 on 2024-03-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsforum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('user_created', models.IntegerField()),
                ('user_assigned', models.IntegerField()),
                ('amount_initial', models.IntegerField()),
                ('amount_final', models.IntegerField()),
                ('time_limit', models.DateTimeField()),
            ],
        ),
    ]
