# Generated by Django 4.1 on 2024-03-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid_posts',
            name='image',
            field=models.ImageField(upload_to='uploads/bid/'),
        ),
    ]
